Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Controllers/BuildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using EpicGames.Tools.Builder.Frontend.Database;
using EpicGames.Tools.Builder.Frontend.Models;


namespace EpicGames.Tools.Builder.Frontend.Controllers
{
    public class BuildController : BaseController
    {
        #region Actions

        /// <summary>
        /// Creates the branch details view.
        /// </summary>
        /// <param name="id">Branch name.</param>
        /// <returns>Branch details view.</returns>

        public ActionResult Branch( int id )
        {
            var model = new BuildBranchModel();

            model.Details = dataContext.SP_GetBranchDetails(id).SingleOrDefault();

            return View(model);
        }

        /// <summary>
        /// Returns the list of build commands for the specified branch.
        /// </summary>
        /// <param name="id">Branch identifier.</param>
        /// <returns>Build command list view.</returns>

        public ActionResult BranchCommands( int id )
        {
            return View(dataContext.SP_GetBranchCommands(id).ToList());
        }

        /// <summary>
        /// Creates the change list details view.
        /// </summary>
        /// <param name="id">Changelist identifier.</param>
        /// <returns>Changelist details view.</returns>

        public ActionResult Changelist( int id )
        {
            var model = new BuildChangelistModel();

            model.ChangelistId = id;
            model.Details = dataContext.SP_GetChangelistDetails(id).SingleOrDefault();

            if (model.Details != null)
            {
                model.Details.Submitter = model.Details.Submitter.Replace('_', '.');
                model.BuildLogs = dataContext.SP_GetChangelistBuildLogs(id, model.Details.Branch).ToList();
            }

            model.CisLogs = dataContext.SP_GetChangelistCisLogs(id).ToList();

            return View(model);
        }

        /// <summary>
        /// Creates the build command details view.
        /// </summary>
        /// <param name="id">Command identifier.</param>
        /// <returns>Build command details view.</returns>

        public ActionResult Command( int id )
        {
            var model = new BuildCommandModel();

            model.Branches = dataContext.SP_GetBranchList().ToList();
            model.Details = dataContext.SP_GetCommandDetails(id).SingleOrDefault();
            model.Machines = dataContext.SP_GetMachineStatus("%").ToList();
            
            var subscriptions = dataContext.SP_GetCommandSubscriptions(id, GetCurrentUserEmail()).ToList();

            model.SubscribedFailed = (subscriptions.Count(s => s.Type == 'F') > 0);
            model.SubscribedSucceeded = (subscriptions.Count(s => s.Type == 'S') > 0);
            model.SubscribedTriggered = (subscriptions.Count(s => s.Type == 'T') > 0);

            return View(model);
        }

        /// <summary>
        /// Retrieves the details for the specified build command.
        /// </summary>
        /// <param name="id">ID of the command.</param>
        /// <returns>Command details view.</returns>

        public ActionResult CommandDetails( int id )
        {
            return View(dataContext.SP_GetCommandDetails(id).SingleOrDefault());
        }

        /// <summary>
        /// Retrieves the build log for the specified build command.
        /// </summary>
        /// <param name="id">ID of the command.</param>
        /// <returns>Command log view.</returns>
        
        public ActionResult CommandLog( int id )
        {
            var model = new BuildCommandLogModel();

            model.BuildLogs = dataContext.SP_GetCommandBuildLogs(id, 0, 50).ToList();
            model.Details = dataContext.SP_GetCommandDetails(id).SingleOrDefault();

            return View(model);
        }

        /// <summary>
        /// Displays the desktop performance page.
        /// </summary>
        /// <returns>Desktop performance view.</returns>

        public ActionResult DesktopPerformance( )
        {
            return View();
        }

        /// <summary>
        /// Disables maintenance mode for the specified build machine.
        /// </summary>
        /// <param name="id">Machine name.</param>
        /// <returns></returns>

        public ActionResult DisableMachineMaintenance( string id )
        {
            dataContext.SP_SetMachineMaintenance(id, 0);

            return null;
        }

        /// <summary>
        /// Enables maintenance mode for the specified build machine.
        /// </summary>
        /// <param name="id">Machine name.</param>
        /// <returns></returns>

        public ActionResult EnableMachineMaintenance( string id )
        {
            dataContext.SP_SetMachineMaintenance(id, 1);

            return null;
        }

        /// <summary>
        /// Creates the build failures view.
        /// </summary>
        /// <returns>Build failures view.</returns>

        public ActionResult Failures( )
        {
            var model = new BuildFailuresModel();

            model.FailedCommands = dataContext.SP_GetFailedCommands(999999).ToList();

            return View(model);
        }

        /// <summary>
        /// Creates the infrastructure view.
        /// </summary>
        /// <returns>Infrastructure view.</returns>

        public ActionResult Infrastructure( )
        {
            return View();
        }

		/// <summary>
		/// Creates the infrastructure machine list view.
		/// </summary>
		/// <returns>Infrastructure machine list view</returns>
        public ActionResult InfrastructureList( )
        {
            return View(dataContext.SP_GetMachineStatus("%").ToList());
        }

		/// <summary>
		/// Locks the specified branch.
		/// </summary>
		/// <param name="id">The ID of the branch to lock.</param>
		/// <returns></returns>
		public ActionResult LockBranch(int id)
		{
			dataContext.SP_SetBranchLockDown(id, 1);

			return null;
		}

        /// <summary>
        /// Returns a build log file.
        /// </summary>
        /// <param name="id">The branch for which the log file was generated.</param>
        /// <param name="param">The path to the log file.</param>
        /// <returns></returns>
        public ActionResult LogFile( string id, string param )
        {
            string path = "file://epicgames.net/Root/UE3/Builder/BuilderFailedLogs/" + id + "/" + param;

            try
            {
                using (var webClient = new WebClient())
                {
                    return Content("<pre>" + webClient.DownloadString(path) + "</pre>");
                }
            }
            catch (Exception e)
            {
                return Content("File not found - " + e.Message);
            }
        }

        /// <summary>
        /// Retrieves the view for a particular build machine.
        /// </summary>
        /// <param name="id">Machine name.</param>
        /// <returns>Build machine details view.</returns>

        public ActionResult Machine( string id )
        {
            var model = new BuildMachineModel();

            model.MachineName = id;

            return View(model);
        }

        /// <summary>
        /// Returns the list of build logs for the specified machine.
        /// </summary>
        /// <param name="id">Machine name.</param>
        /// <returns>Build log list view.</returns>

        public ActionResult MachineBuildLogs( string id )
        {
            return View(dataContext.SP_GetMachineBuildLogs(id, 0, 25).ToList());
        }

        /// <summary>
        /// Retrieves the details for the specified build machine.
        /// </summary>
        /// <param name="id">Name of the machine.</param>
        /// <returns>Machine details view.</returns>

        public ActionResult MachineDetails( string id )
        {
            return View(dataContext.SP_GetMachineDetails(id).SingleOrDefault());
        }

        /// <summary>
        /// Creates the build status view.
        /// </summary>
        /// <returns>Build status view.</returns>

        public ActionResult Status( )
        {
            var model = new BuildStatusModel();

            model.Branches = dataContext.SP_GetBuildBranches().ToList();

            return View(model);
        }

        /// <summary>
        /// Creates a status view for all build commands.
        /// </summary>
        /// <returns></returns>

        public ActionResult StatusCommands( )
        {
            return View(dataContext.SP_GetBuildCommands().ToList());
        }

        /// <summary>
        /// Stops the in-progress build with the specified identifier.
        /// </summary>
        /// <param name="id">Build identifier.</param>
        /// <returns></returns>

        public ActionResult Stop( int id )
        {
            dataContext.SP_StopCommand(id, GetCurrentUserName());

            return null;
        }

        /// <summary>
        /// Subscribes the current user to build command notifications.
        /// </summary>
        /// <param name="id">Build command identifier.</param>
        /// <param name="type">The type of subscription (trigger, success, failure).</param>
        /// <returns>Nothing.</returns>

        public ActionResult SubscribeCommand( int id, byte type )
        {
            dataContext.SP_AddCommandSubscription(id, type, GetCurrentUserEmail());

            return null;
        }

        /// <summary>
        /// Triggers a build command.
        /// </summary>
        /// <param name="id">The ID of the command to trigger.</param>
        /// <returns>Nothing.</returns>

        public ActionResult Trigger( int id )
        {
            dataContext.SP_TriggerCommand(id, GetCurrentUserName());

            return null;
        }

        /// <summary>
        /// Displays the UE4 build times chart page.
        /// </summary>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/CommandDetails.cshtml
@model EpicGames.Tools.Builder.Frontend.Database.SP_GetCommandDetailsResult

@{
    Layout = null;

    string img;
    string title;

    if (Model.StartTime.HasValue)
    {
        img = "spinner.gif";
        title = "New Build in Progress since " + Model.StartTime.Value.ToLocalTime().ToString() + " on " + Model.Machine + " triggered by " + Model.Operator;
    }
    else
    {
        if (Model.LastAttemptedChangeList == Model.LastGoodChangeList)
        {
            img = "tick.png";
            title = "Last Build Succeeded";
        }
        else
        {
            img = "cross.png";
            title = "Last Build Failed";
        }
    }
}

@functions{
    string TriggerDelayToString (int delay)
    {
        string result = "";
        TimeSpan timespan = TimeSpan.FromMinutes(delay);

        if (timespan.TotalDays >= 1)
        {
            result += ((int)timespan.TotalDays).ToString() + " day(s) ";
        }

        if (timespan.Hours > 0)
        {
            result += timespan.Hours.ToString() + " hour(s) ";
        }

        if (timespan.Minutes > 0)
        {
            result += timespan.Minutes.ToString() + "min ";
        }

        return result;
    }
}

<div class="grid4">
    <a name="details"></a><h2>Command Details</h2>

    <p>
        This command is configured to be triggered <strong>@((Model.NextTriggerDelay.HasValue) ? "automatically every " + TriggerDelayToString(Model.NextTriggerDelay.Value) : "manually").</strong>
    </p>

    <table class="tableKeyValue">
        <tbody>
            <tr>
                <th>Name:</th>
                <td>
                    <img class="icon" src="~/Content/Themes/Base/Images/@img" alt="State" title="@title" />
                    @Model.Description
                </td>
            </tr>
            <tr>
                <th>Applies to Branch:</th>
                <td>@Html.ActionLink(Model.Branch, "Branch", "Build", new { id = Model.BranchConfigID }, null)</td>
            </tr>
            <tr>
                <th>Applies to Platform:</th>
                <td>@Model.Platform</td>
            </tr>
            <tr>
                <th>Last Operator:</th>
                <td>
                    @if (Model.Operator != "AutoTimer")
                    {
                        @Html.ActionLink(@Model.Operator, "UserProfile", "Home", new { id = @Model.Operator }, null)
                        <a href="mailto:@(Model.Operator + "@epicgames.com")?subject=Regarding build command @Model.Command on branch @Model.Branch"><img class="icon" src="~/Content/Themes/Base/Images/iconOutlook.png" alt="IM" /></a>
                        <a href="sip:@(Model.Operator + "@epicgames.com")"><img class="icon" src="~/Content/Themes/Base/Images/iconLync.png" alt="Send Email" /></a>
                    }
                    else
                    {
                        @Model.Operator
                    }
                </td>
            </tr>
            <tr>
                <th>Last Good Label</th>
                <td>@Model.LastGoodLabel</td>
            </tr>
            <tr>
                <th>Last Good Changelist:</th>
                <td>@Html.ActionLink("CL " + Model.LastGoodChangeList.ToString(), "Changelist", "Build", new { id = Model.LastGoodChangeList }, null) on @Model.LastGoodDateTime.ToString()</td>
            </tr>
            @if (Model.LastAttemptedChangeList != Model.LastGoodChangeList)
            {
                <tr class="bad">
                    <th>Last Attempted Changelist:</th>
                    <td>@Html.ActionLink("CL " + Model.LastAttemptedChangeList.ToString(), "Changelist", "Build", new { id = Model.LastAttemptedChangeList }, null) on @Model.LastAttemptedDateTime.ToString()</td>
                </tr>
            }
            @if (Model.Killing)
            {
                <tr>
                    <th>Is Being Killed By:</th>
                    <td>@Model.Killer</td>
                </tr>
            }
            @if (Model.NextTrigger.HasValue)
            {
                <tr>
                    <th>Next Trigger:</th>
                    <td>@Model.NextTrigger.Value.ToString()</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="grid2">
    <h2>&nbsp;</h2>

    @if (Model.Type == 3)
    {
        <a class="button" href="@Url.RouteUrl(new { action = "Promote", controller = "Build", id = Model.ID })" title="Stop Command">Promote a Label</a>
    }
    else if (Model.StartTime.HasValue || Model.Pending)
    {
        <a class="button" href="javascript: stopCommand(@Model.ID)" title="Stop Command">Stop Command</a>
    }
    else
    {
        <a class="button" href="javascript: triggerCommand(@Model.ID)" title="Trigger Command">Trigger Command</a>
    }
</div>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/DesktopPerformance.cshtml
@{
    ViewBag.Title = "Build System";
    ViewBag.Description = "UE4 Build Times";
}


<section>
    <div class="grid6">
        <span class="linkBack">
            @Html.ActionLink("Build Status", "Status", "Build")
        </span>

        <span class="fr">
            <a href="#performance">Performance</a>
        </span>
    </div>
</section>

<section class="clearfix">
    <div class="grid6">
        <a name="performance"></a><h2>Performance</h2>
        
        <p>
            Desktop performance of selected builds since <strong>8/3/2012</strong>:
            <img id="desktopPerformanceChart" class="chart" src="@Url.RouteUrl(new { action = "DesktopPerformance", controller = "Chart" })" alt="Chart" />
        </p>
    </div>
</section>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/Failures.cshtml
@model EpicGames.Tools.Builder.Frontend.Models.BuildFailuresModel

@{
    ViewBag.Title = "Build System";
    ViewBag.Description = "Current Status";
}

<section>
    <div class="grid6">
        <span class="linkBack">
            @Html.ActionLink("Build Status", "Status", "Build")
        </span>

        <span class="fr">
            <a href="#failing">All Failing Builds</a>
        </span>
    </div>
</section>

<section>
    <div class="grid6">
        <a name="failing"></a>

        <h2>All Failing Builds</h2>

        @if (Model.FailedCommands.Count() > 0)
        {
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Branch</th>
                        <th>Days Broken</th>
                        <th>Last Attempted</th>
                        <th class="highlight">Last Good</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var c in Model.FailedCommands)
                    {
                        <tr class="bad">
                            <td>
                                <img src="~/Content/Themes/Base/Images/cross.png" alt="Bad" />
                                @c.Description
                            </td>
                            <td>@Html.ActionLink(@c.Branch, "Branch", "Build", new { id = c.Branch }, new { title = "Click for branch details" })</td>
                            <td>@c.DaysBroken</td>
                            <td>@Html.ActionLink("CL " + c.LastAttemptedChangeList.ToString(), "Changelist", "Build", new { id = c.LastAttemptedChangeList.ToString() }, null)</td>
                            <td class="highlight">@Html.ActionLink("CL " + c.LastGoodChangeList.ToString(), "Changelist", "Build", new { id = c.LastGoodChangeList.ToString() }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div>There are no build failures at this time.</div>
        }

        <a class="linkUp" href="#top">Back to top</a>
    </div>
</section>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/InfrastructureList.cshtml
@model IEnumerable<EpicGames.Tools.Builder.Frontend.Database.SP_GetMachineStatusResult>

@{
    Layout = null;

    DateTime LatestBuilderVersion = Model.Where(m => m.Deployed).Max(m => m.Version);
}

<section>
    <div class="grid6">
        <a name="active"></a>

        <h2>Active Builders</h2>

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th class="enum">Last Updated</th>
                    <th class="enum">State</th>
                    <th>Current Operation</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    if (m.Deployed && !string.Equals(m.MachineName, m.MachineLock, StringComparison.CurrentCultureIgnoreCase))
                    {
                        if (!m.CurrentTime.HasValue || (DateTime.UtcNow.Subtract(m.CurrentTime.Value).TotalDays <= 30.0))
                        {
                            if (!m.CurrentTime.HasValue || (DateTime.UtcNow.Subtract(m.CurrentTime.Value).TotalHours > 4.0))
                            {
                                m.State = "Offline";
                            }
                        
                            <tr class="@((m.Version == LatestBuilderVersion) ? "current" : "")">
                                <td>@Html.ActionLink(@m.MachineName, "Machine", "Build", new { id = @m.MachineName }, null)</td>
                                <td class="enum">@m.Version.ToString()</td>
                                <td class="enum @("state" + m.State)">@m.State</td>
                                <td>@m.CurrentStatus</td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>

        <a class="linkUp" href="#top">Back to top</a>
    </div>
</section>

<section>
    <div class="grid6">
        <a name="maintenance"></a><h2>In Maintenance</h2>

        @if (Model.Count(m => m.Deployed && string.Equals(m.MachineName, m.MachineLock, StringComparison.CurrentCultureIgnoreCase)) > 0)
        {
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th class="enum">Last Updated</th>
                        <th class="enum">State</th>
                        <th class="numeric">Current Operation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var m in Model)
                    {
                        if (m.Deployed && string.Equals(m.MachineName, m.MachineLock, StringComparison.CurrentCultureIgnoreCase))
                        {
                            if (m.CurrentTime.HasValue && (DateTime.UtcNow.Subtract(m.CurrentTime.Value).TotalDays <= 30))
                            {
                                <tr class="@((m.Version == LatestBuilderVersion) ? "current" : "")">
                                    <td>@Html.ActionLink(@m.MachineName, "Machine", "Build", new { id = @m.MachineName }, null)</td>
                                    <td class="enum">@m.Version.ToString()</td>
                                    <td class="enum @("state" + m.State)">@m.State</td>
                                    <td></td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>None of the builders are in maintenance mode right now.</p>
        }

        <a class="linkUp" href="#top">Back to top</a>
    </div>

    <div class="grid6">
        <a name="inactive"></a><h2>Inactive Builders</h2>

        <p>The following build machines haven't been used for more than 30 days:</p>

        <p class="machineList">
            @foreach (var m in Model)
            {
                if (m.Deployed && m.CurrentTime.HasValue && (DateTime.UtcNow.Subtract(m.CurrentTime.Value).TotalDays > 30))
                {
                    <span>@Html.ActionLink(@m.MachineName, "Machine", "Build", new { id = @m.MachineName }, null)</span>
                }
            }
        </p>

        <a class="linkUp" href="#top">Back to top</a>
    </div>

    <div class="grid6">
        <a name="testing"></a><h2>Test Builders</h2>

        <p>The following builders were previously used for testing:</p>

        <p class="machineList">
            @foreach (var m in Model)
            {
                if (!m.Deployed)
                {
                    <span>@Html.ActionLink(@m.MachineName, "Machine", "Build", new { id = @m.MachineName }, null)</span>
                }
            }
        </p>

        <a class="linkUp" href="#top">Back to top</a>
    </div>
</section>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/StatusCommands.cshtml
@model IEnumerable<EpicGames.Tools.Builder.Frontend.Database.SP_GetBuildCommandsResult>

@{
    Layout = null;

    const int RecentlyFailedDays = 7;
}


<div class="grid6">
    <a name="latestfailures"></a><h2>Latest Failures</h2>

    @{
        int failing = Model.Count(c => !c.BuildStarted.HasValue && (c.LastGoodChangelist != c.LastAttemptedChangelist));
        
        if (failing > 0)
        {
            <p>
                <strong>@failing.ToString()</strong> of @Model.Count().ToString() build commands are currently failing.
                The following commands failed within the last @RecentlyFailedDays.ToString() days:

                <span class="fr">[ @Html.ActionLink("Show all failing commands", "Failures", "Build") ]</span>
            </p>

            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Branch</th>
                        <th class="numeric">Days Broken</th>
                        <th class="enum">Last Attempted</th>
                        <th class="enum">Last Good</th>
                        <th class="enum">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var c in Model)
                    {
                        if (!c.BuildStarted.HasValue && (c.LastAttemptedChangelist != c.LastGoodChangelist))
                        {
                            if ((DateTime.UtcNow - c.LastAttemptedDateTime).TotalDays <= RecentlyFailedDays)
                            {
                                Html.RenderPartial("_StatusCommand", c);
                            }
                        }
                    }
                </tbody>
            </table>
        }
        else
        {
            <div>There are no build failures at this time.</div>
        }
    }

    <a class="linkUp" href="#top">Back to top</a>
</div>

<div class="grid6">
    <a name="building"></a><h2>Currently Building</h2>

    @{
        int building = Model.Count(c => c.BuildStarted.HasValue && !c.Pending);
        
        if (building > 0)
        {
            <p>
                <strong>@building.ToString()</strong> of @Model.Count().ToString() build commands are currently executing:
            </p>

            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Branch</th>
                        <th class="numeric">Days Broken</th>
                        <th class="enum">Last Attempted</th>
                        <th class="enum">Last Good</th>
                        <th class="enum">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var c in Model)
                    {
                        if (c.BuildStarted.HasValue && !c.Pending)
                        {
                            Html.RenderPartial("_StatusCommand", c);
                        }
                    }
                </tbody>
            </table>
        }
        else
        {
            <div>There are no active build commands at this time.</div>
        }
    }

    <a class="linkUp" href="#top">Back to top</a>
</div>

<div class="grid6">
    <a name="pending"></a><h2>Pending Builds</h2>

    @{
        int pending = Model.Count(c => c.Pending);
        
        if (pending > 0)
        {
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Branch</th>
                        <th class="numeric">Days Broken</th>
                        <th class="enum">Last Attempted</th>
                        <th class="enum">Last Good</th>
                        <th class="enum">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var c in Model)
                    {
                        if (c.Pending)
                        {
                            Html.RenderPartial("_StatusCommand", c);
                        }
                    }
                </tbody>
            </table>
        }
        else
        {
            <div>There are no pending builds at this time.</div>
        }
    }

    <a class="linkUp" href="#top">Back to top</a>
</div>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/UE4BuildTimes.cshtml
@{
    ViewBag.Title = "Build System";
    ViewBag.Description = "UE4 Build Times";
}


<section>
    <div class="grid6">
        <span class="linkBack">
            @Html.ActionLink("Build Status", "Status", "Build")
        </span>

        <span class="fr">
            <a href="#example">Example Game Win64</a> |
            <!--<a href="#gear">Gear Game Win64</a> |-->
            <a href="#fortnite">Fortnite Game Win64</a> |
            <a href="#udk">UDK Game Win64</a>
        </span>
    </div>
</section>

<section class="clearfix">
    <div class="grid6">
        <a name="example"></a><h2>Example Game Win64</h2>
        <p>
            Project build times over the last <strong>60</strong> days:
            <span class="fr">[ Download as CSV - @Html.ActionLink("60 Days", "BuildTimes", "Export", new { counter = 1437, days = 60 }, null) | @Html.ActionLink("All Time", "BuildTimes", "Export", new { counter = 1437, days = 9999 }, null) ]</span>
            <img class="chart" src="@Url.RouteUrl(new { action = "UE4BuildTimes", controller = "Chart", counter = 1437, days = 60 })" alt="Chart" />
        </p>

        <a name="udk"></a><h2>UDK Game Win64</h2>
        <p>
            Project build times over the last <strong>60</strong> days:
            <span class="fr">[ Download as CSV - @Html.ActionLink("60 Days", "BuildTimes", "Export", new { counter = 1438, days = 60 }, null) | @Html.ActionLink("All Time", "BuildTimes", "Export", new { counter = 1438, days = 9999 }, null) ]</span>
            <img class="chart" src="@Url.RouteUrl(new { action = "UE4BuildTimes", controller = "Chart", counter = 1438, days = 60 })" alt="Chart" />
        </p>
    </div>
</section>

Development/Tools/Builder2/EpicGames.Tools.Builder.Frontend/Views/Build/_ChangelistBuildLogEntry.cshtml
@model EpicGames.Tools.Builder.Frontend.Database.SP_GetChangelistBuildLogsResult

@{
    Layout = null;
}

@{
    string img;
    string title;
    bool died = false;

    if (Model.CurrentStatus == "Succeeded")
    {
        img = "tick.png";
        title = "Command Succeeded";
    }
    else if (Model.CurrentStatus == "Failed")
    {
        img = "cross.png";
        title = "Command Failed";
    }
    else if ((DateTime.UtcNow - Model.BuildStarted.Value) < TimeSpan.FromHours(4))
    {
        img = "spinner.gif";
        title = "Command in Progress since " + Model.BuildStarted.Value.ToLocalTime().ToString();
    }
    else
    {
        img = "skull.png";
        title = "Command died";
        died = true;
    }
                            
    <tr class="@((Model.CurrentStatus == "Failed") ? "bad" : "good")" title="@title">
        <td class="string">
            <img src="~/Content/Themes/Base/Images/@img" alt="State" />

            @if (Model.CommandDescription != null)
            {
                <text>@Html.ActionLink(Model.CommandDescription, "Command", "Build", new { id = Model.CommandID }, null)</text>
            }
            else
            {
                <text>@Model.Command</text>
            }
        </td>
        <td class="string">
            @Html.ActionLink(@Model.Machine, "Machine", "Build", new { id = Model.Machine }, null)
        </td>
        <td class="enum">
            @Model.BuildStarted.Value.ToLocalTime().ToString()
        </td>
        <td class="enum">
            @if ((Model.CurrentStatus == "Succeeded") || (Model.CurrentStatus == "Failed"))
            {
                if (Model.BuildEnded.HasValue)
                {
                    <text>@((Model.BuildEnded.Value - Model.BuildStarted.Value).ToString("hh\\:mm\\:ss"))</text>
                }
                else
                {
                    <text>n/a</text>
                }
            }
            else if (died)
            {
                <text>-</text>
            }
            else
            {
                <text>@((DateTime.UtcNow - Model.BuildStarted.Value).ToString("hh\\:mm\\:ss"))</text>
            }
        </td>
        <td class="enum">
            @if (!string.IsNullOrEmpty(Model.DetailedLogPath))
            {
                
                <a href="file://epicgames.net/Root/UE3/Builder/BuilderFailedLogs/@ViewBag.Branch/@Model.DetailedLogPath" onclick="javascript: popupPage('@Url.RouteUrl(new { action= "LogFile", controller = "Build", id = ViewBag.Branch, param = Model.DetailedLogPath })'); return false;"><img src="~/Content/Themes/Base/Images/doc.png" alt="Log file" /></a>
            }
        </td>
    </tr>
}